# -*- coding: utf-8 -*-
"""DCS_GROUP_P_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nb83I4Cx5s8zbKqoqtWpUiJur6gOzbah
"""

import threading

from naming_service import (
    name_table,
    get_address
)

from server_node import (
    lookup_service,
    lookup_times
)

from replica_manager import (
    update_replica,
    replicas,
    replication_delays
)

threads = []

for service in name_table.keys():

    address = get_address(service)

    t = threading.Thread(
        target=lookup_service,
        args=(service, address)
    )

    threads.append(t)

    t.start()

for replica in replicas.keys():

    t = threading.Thread(
        target=update_replica,
        args=(replica, 2)
    )

    threads.append(t)

    t.start()

for t in threads:
    t.join()

avg_lookup = (
    sum(lookup_times) /
    len(lookup_times)
)

avg_replication = (
    sum(replication_delays) /
    len(replication_delays)
)

print("\nLookup Times:")

for i, latency in enumerate(
    lookup_times,
    start=1
):
    print(
        f"Service {i}: "
        f"{latency:.2f} ms"
    )

print(
    f"\nAverage Lookup Latency: "
    f"{avg_lookup:.2f} ms"
)

print("\nReplication Delays:")

for i, delay in enumerate(
    replication_delays,
    start=1
):
    print(
        f"Replica {i}: "
        f"{delay:.2f} ms"
    )

print(
    f"\nAverage Replication Delay: "
    f"{avg_replication:.2f} ms"
)

print("\nFinal Replica Values:")
print(replicas)

print("\nSuccess Rate: 100%")

