# -*- coding: utf-8 -*-
"""DCS_GROUP_P_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nb83I4Cx5s8zbKqoqtWpUiJur6gOzbah
"""

name_table = {
    "spb.unisza.edu.my": "192.168.1.10:5000",
    "kelip.unisza.edu.my": "192.168.1.10:5001",
    "kelipfik.unisza.edu.my": "192.168.1.10:5002",
    "kelipfbim.unisza.edu.my": "192.168.1.10:5003",
    "portal.unisza.edu.my": "192.168.1.10:5004"
}

def get_address(service_name):
    return name_table.get(service_name)

