# -*- coding: utf-8 -*-
"""DCS_GROUP_P_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nb83I4Cx5s8zbKqoqtWpUiJur6gOzbah
"""

import time
import random

replicas = {
    "A": 1,
    "B": 1,
    "C": 1
}

replication_delays = []

def update_replica(replica_id, value):

    delay = random.uniform(0.1, 0.5)

    time.sleep(delay)

    replicas[replica_id] = value

    replication_delays.append(delay * 1000)

    print(
        f"Replica {replica_id} "
        f"updated to {value} "
        f"after {delay*1000:.2f} ms"
    )

