# -*- coding: utf-8 -*-
"""DCS_GROUP_P_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nb83I4Cx5s8zbKqoqtWpUiJur6gOzbah
"""

import time
import random

lookup_times = []

def lookup_service(service_name, address):

    start = time.time()

    time.sleep(random.uniform(0.05, 0.15))

    latency = (time.time() - start) * 1000

    lookup_times.append(latency)

    print(
        f"{service_name} resolved to "
        f"{address} "
        f"({latency:.2f} ms)"
    )

